### ISSUE TITLE
Windows native installation/usage exploration

### ISSUE THREAD

**Issue by mih** [datalad-handbook/book#132]
FTR: This is what I find to be the simplest installation procedure on Win10 after some trial-and-error

### Install Conda
- pick latest PY3 installer: https://docs.conda.io/en/latest/miniconda.html
- keep everything on default (do not add to PATH)
- this will also install Python
- from now on any further action must take place in the "Anaconda Prompt" (a preconfigured terminal shell)

### Install Git
- `conda install -c conda-forge git` (must be from conda-forge, anaconda version does not provide `cp`)

### Install git-annex
- Download installer from https://downloads.kitenet.net/git-annex/windows/current/
- Install into the miniconda `Library` directory, e.g. C:\Users\mih\Miniconda3\Library

### Install datalad
- it is possible to install datalad via conda too (`conda install -c conda-forge datalad`) but it only supports the 0.11 version, hence is irrelevant in this context
- install datalad via `pip`  as usual

How functional datalad actually is on Win10 if installed this way is subject to further exploration.

### (Confirmed) features

- [x]  OpenSSH:  `OpenSSH_7.9p1, OpenSSL 1.1.1a  20 Nov 2018`
- [x] git-annex: `All 168 tests passed`
- [ ] `datalad.support.tests.test_gitrepo` https://github.com/datalad/datalad/issues/3635
- [ ] `datalad.support.tests.test_annexrepo` https://github.com/datalad/datalad/issues/3636
- [ ] `datalad.core` tests https://github.com/datalad/datalad/issues/3633
- [ ] `datalad.distribution.tests.test_clone` https://github.com/datalad/datalad/pull/3640
- [x] `datalad.distribution.tests.test_install`
- [ ] `datalad.distribution.tests.test_get` https://github.com/datalad/datalad/issues/3634
- [ ] `datalad.support.tests.test_ssh*`

**Comment by mih** [comment]
Installing this way does not provide the `cp` command, which is needed by git-annex. It would be installed by git4win. Conda itself does not seem to provide a `coreutils` package for windows. This needs to be resolved on way or another.

**Comment by mih** [comment]
We might want to consider recommending the installation of https://tortoisegit.org/

It provides Git integration into the explorer (unclear if anyhow useful for us), its startup wizzard support SSH key generation, and identity setup.

**Comment by mih** [comment]
We have now settled on going largely native by default. This should not prevent or discourage people from alternative routines that work for them.
