### ISSUE TITLE
Pre-Release TODOs

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#302]
Here are a couple of large points/TODOs (no claims made to completeness) of things I'd like to have prepared prior to a release:

- [x] The sections "What you really need to know" (#295) and the "Cheat sheet" (#157) would be really cool to have ready
- [x] Adjust the installation instructions and get rid of all the warnings (PR'ed in #337)
- [x] provide something that resembles a tagged ``DataLad-101`` dataset, at least to view in total and to try out the final chapters on file system operations and interactions with the history. For earlier chapters, its yet (I believe) impossible to reset the state of a dataset recursively... Also needs a short explanation how to use the tagged repository.
- [x] The sections and chapters after the section on `datalad containers-run` are relatively unconnected to eachother, I should at least provide summaries at the end of chapters and try to connect them a bit more. --> first attempts in #307
- [x] Do another release of the handbook. ~Maybe ``v0.2``~. The release version can match the DataLad version, i.e. ``v0.12.0``

**Comment by adswa** [comment]
This can be closed as I'll do the release now.
