### ISSUE TITLE
Release management for the handbook

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#444]
A few recent issues highlighted a core deficiency of the handbook: We don't yet have any release management.

- #439 voiced interest in permalinks to the latest "released" version
- https://github.com/datalad/datalad/issues/4356 showed that in some occasions, the book progresses faster than DataLad's own release cycle - we exchanged ``datalad publish`` with ``datalad push`` in #417 when it will only be part of DataLad's not-even-scheduled-yet 0.13 release.

The only proper release was the ``0.12.0`` release, matching the release of DataLad ``0.12.0``. In order to be up-to-date, but not in the future, the handbook will need to follow DataLad's releases. Else, it can happen that users attempt to follow a command in the handbook but can't -- that is a worst case scenario and currently happening. 

Below I'm trying to summarize a potential way to handle handbook development. But I'm new to all those aspects, so let me know if you see a problem or a better way cc @mih, @yarikoptic, @bpoldrack, @kyleam 

#### Sketch of release management
- The default version on readthedocs that [handbook.datalad.org](http://handbook.datalad.org) should redirect to needs to be a version that matches the currently released functionality of DataLad. I can see this working in a "major" release kind of way (Minor version branches are possible, but I'm doubting whether minor releases in DataLad will cause large enough book changes to make this finer granularity worthwhile):
    - one branch is declared to be the "stable" release. All handbook changes that involve functionality that works in the latest minor release of ``0.12.x`` are PRed against this branch. There is one half-hearted attempt at this with the ``0.12`` branch of the handbook that we could pick up on. This branch would contain changes across minor DataLad releases within the ``0.12`` major release, i.e., whatever works in the latest ``0.12.x`` release is in there, with no finer granularity. Downside: a user with DataLad ``0.12.1`` could read the chapter on RIA stores and would fail to execute the command.
    - We could have this branch be rendered as [handbook.datalad.org/en/0.12/](http://handbook.datalad.org/en/0.12/) (Pro: makes the version transparent in the url, Con: once ``0.13`` comes it won't link to the latest handbook version) or rendered as [handbook.datalad.org/en/stable/](http://handbook.datalad.org/en/stable/) (Pro: The same link will always point to the latest "stable" functionality, Con: the version is not as transparent, and what used to be in the handbook for ``0.12`` under a given link may not be anymore when ``0.13`` is released), or both (both links point to the same content). I'm favoring the third option 
    - Regardless of which link the ``0.12`` version ends up in, once ``0.13.x`` is released, the ``0.12`` branch will be forever be available under its latest state on [handbook.datalad.org/en/0.12](http://handbook.datalad.org/en/0.12/), and [handbook.datalad.org](http://handbook.datalad.org) by default points to a ``0.13`` version.
- Readthedocs "latest" version, as far as I can see, points to ``master``. This makes handbook.datalad.org/en/latest the "developer version" of the handbook. If one installs DataLad from its latest commits instead of its releases, this handbook version is the one to read. All features that are not yet in a minor or major release will be PRed against master. This saves the "stable" branch from containing features that are not yet released.
- However, this makes master the same unmanaged timemachine that it currently is. Should there be functionality that content in master talks about, but that will not be part of the next major datalad release, cherry-picking a ``0.13`` branch out of master will be a similar deep dive into a sewage of merge conflicts as the upcoming process of getting only currently released content from master into ``0.12`` will be. I don't know, though, whether this can be in any way alleviated - the handbook PRs are much more interdependent on each other. 
- ``0.12`` is regularly merged into master.
- When a DataLad major release happens, the handbook will get a matching major release branch. This branch will become the default target for [handbook.datalad.org](http://handbook.datalad.org), and subsequently works just as the ``0.12`` branch before.
- A major DataLad release will be accompanied by a handbook release with matching version.

#### TODOs to get there
- [ ] Update the ``0.12`` branch to all development in master that matches currently released functionality. 
- [ ] Change default version on readthedocs from latest to either stable or `0.12`
- [ ] Make readthedocs stable version point to the `0.12` branch
- [ ] [handbook.datalad.org/en/latest](http://handbook.datalad.org/en/latest) should get a front-page disclaimer that it contains content that potentially comes from the future
- [ ] Update the contributing page of the handbook to explain the release management
- submit all future PRs against 0.12 unless they contain yet-to-be-released content

#### Potential problems
- This will make it harder for external people to collaborate and submit a PR. By default, when they clone this repository, they will put changes on top of master. Master may be substantially ahead of ``0.12`` and rebasing may not be straightforward, depending on how much the current stable branch  and ``master`` deviated already.
- Merge conflicts from hell will ensue if there are large differences to structural aspects of the book, for example a major toctree reformating as done in #367, or infrastructural changes as will happen when  #433 is fixed.

**Comment by kyleam** [comment]
My two cents: I wouldn't try to handle this with branches for versions.  I think the potential problems you mention are bad enough to not be worth the trouble.

I'm sure I'm not capturing everything you want to achieve above, but I'd suggest something like this:

* Have a single branch.

* Freely add content that deals with unreleased DataLad functionality, along with a canned note/alert that the feature is under development and hasn't made it into a release.

* When a DataLad feature release is cut, prune these notes.  Add a tag that corresponds to the DataLad release.  Somehow freeze/capture the readthedocs output.  Expose some number of recent ones.  But they are what they are; don't go back and make changes.

**Comment by mih** [comment]
Thanks @kyleam for your feedback on this!  I think the idea to use notes to identify features that will be available in a future datalad version. It is simple, non-invasive and covers most cases. I am easily convinced that we should adopt it.  The  scenario that it doesn't cover is something like the  `publish->push` change. It is a stand-in for a relatively large scale change where individual notes aren't really suitable. The only way that I can see (without reaching for branches) is to simply not make such changes.

**Comment by bpoldrack** [comment]
Agree. I woudln't make contributing to (and maintaining) the handbook repository as complicated as an actual software repo. It should be rather easy for non-developers to open a PR and add or fix something. This disqualifies the branches approach, I think.

However, it would be nice to have some assurance that it's actually targeting current release of datalad and enforce this:

> The only way that I can see (without reaching for branches) is to simply not make such changes.

So, if we can find a good way to run the examples as actual tests against released datalad - that would solve it, I guess (and would be valueable independently of the release aspect).

**Comment by jadecci** [comment]
Dear all, I'm not sure if this is relevant to this issue, or if I should open another issue. I'm trying to install datalad with pip3 on OSX,  but this doesn't actually work for version 0.12.0rc6 (same error as in https://github.com/datalad/datalad/issues/4021). The workaround for me is to install version 0.12.1 or later instead. Maybe this could be taken into consideration for choosing the version, or just stick to pip instead of pip3?

**Comment by mih** [comment]
If you install datalad for the first time, it best to go for the latest release. In this case that would be 0.12.5.

**Comment by jadecci** [comment]
That would work for normal usage. However, I'm trying to follow the example in the handbook. As mentioned in the post here:
> Downside: a user with DataLad 0.12.1 could read the chapter on RIA stores and would fail to execute the command.
 Maybe there could just be notes at places where the commands won't work at later releases?

**Comment by yarikoptic** [comment]
Thank you @adswa for raising it up!  I have read about notes etc.  I think 

- it would be lovely in both handbook **and** datalad docstrings add indication about when any given command came to life (or expected to be deprecated).  Python docs, numpy docs IIRC have that, they say smth like "Introduced in Python 3.3".  So I am all for "notes" but I feel that they could be persistent
- since the handbook matured quite a bit, I think it could be quite feasible to maintain two branches, exactly the same as it is done in datalad codebase:  `master` and `maint`. `maint` could contain fixes and additions relevant to a released version(s) of datalad, and have handbook releases follow that branch until main codebase maint becomes based on master again (i.e. major release).
  - contributions to `maint` could be done by informed contributors or just cherry picked if contributed directly to master
- default version of handbook users visit is the released (tagged, most likely from maint, not master) version.  In docs.datalad.org we only recently switched to that too since people ran into API documentation which was not yet released. 
- "latest" is confusing.  "stable" - I don't know what it really means ;)  I know that "master" has no meaning to non-git people.  But we are talking about documentation for a git-based project.  I think it might be worthwhile to make 1:1 correspondence between branches and then replace "stable" with "release", and possibly retain versions for a few major releases (which we know are still used).
- would be cool if handbook releases managed to follow datalad releases

Once again -- thank you for raising this question and working on the datalad handbook.

**Comment by adswa** [comment]
Thank you everyone for your input, I really appreciate it. Here is the solution that I have settled on based on your thoughts and my thoughts:

- handbook releases follow major DataLad releases. This means, the upcoming DataLad `0.13.0` will be accompanied by a DataLad Handbook `0.13.0`. Minor DataLad releases will not be accompanied by minor Handbook releases.
- http://handbook.datalad.org/en/stable/ points to the last released version of the handbook. Currently, this will thus point to the handbook version of the `0.12.0` release in January 2020, and soon it will point to the released `0.13.0` handbook version (May 2020)
-  For each major release, an archiving branch is created that freezes the state of the handbook at this major release. Currently, there really is only one major release, and this is ``0.12.0``. These archiving branches are published on readthedocs and identified with the major release version: http://handbook.datalad.org/en/0.12/. The purpose of these branches and readthedocs renderings is to archive the handbook at release stages in the easiest accessible way possible.
- The archiving branches get a frontpage note (as I have added one to the `0.12` branch right now: http://handbook.datalad.org/en/0.12/) that highlights that the viewed handbook version is a) archived, b) in a specific handbook release version, c) that this version does not mean that it documents *all* functionality of the matching  DataLad release version but represents the state of the handbook at this time. It further points to ``stable`` as the last released handbook version, and to `latest` as the up-to-date handbook version with general content fixes, additions, and improvements. I will protect these archiving branches from accidental additions.
- All PRs of the handbook are against ``master`` and the `latest` version of the handbook is built from ``master``. General released functionality of the corresponding major DataLad release and general fixes or improvements to the handbook can go straight into master after review from at least one suitable DataLad core developer.  
- I will make sure to not repeat the mistakes of ``push`` and ``create-sibling-ria``: Unreleased DataLad functionality can be documented here and PR'ed, but it will not be merged unless with a note on required minor DataLad version. If this isn't possible (no released minor DataLad version yet, or expected changes in API or behavior) the PR will simply be kept open. This will make the ``latest``  readthedocs version the most suitable version for people to read - it will likely always be the prettiest and most extensive one, but starting from ``0.13`` I hope that it will also only contain descriptions that regular users can get from pip or Neurodebian.
- Thus: no separate branches (easier to maintain, manage contributions, and contribute to), and instead all of the "hot DataLad shit" is kept on GitHub until the world is ready to see it and also get it from DataLad.
- Even though ``latest`` is the preferred version that users should read, the `stable` version may be suitable for some consumption cases. One is: it has a nicer front page in its PDF version (it simply says ``Release 0.12`` and not ``Release 0.12.SHASUMhcasfgrvdswbvjlfölaösldnlkbre2134353``), and another is that it is a "major" version that may be useful to attach to grants/goals/... to show progress, stable releases etc,  ... And there is also a way to provide "hotfixes" to the `stable` version of readthedocs: cut a minor handbook release from a branch that is based on the last release and includes a fix to the discovered problem. If it turns out that there is a fundamental flaw or error in the latest released version of the handbook, this can update the ``stable`` rendering. The archiving branch will need to point to this major version in its highest minor version.

> it would be lovely in both handbook and datalad docstrings add indication about when any given command came to life (or expected to be deprecated). Python docs, numpy docs IIRC have that, they say smth like "Introduced in Python 3.3". So I am all for "notes" but I feel that they could be persistent

I agree with this. From my own experiences, there are plenty of people that still use `0.11.x` for example and therefore I believe that for a very long time onward, there will be many people that use `0.12.x` instead of ``0.13``. Since the handbook is "based on DataLad version ``0.12``or higher", it is fair that everything requires *at least* ``0.12``, but that everything that requires something more recent is tagged with a note. This reminds people of the most obvious solution to a "command not found" error and also reminds them to keep their DataLad version up to date.

**Comment by yarikoptic** [comment]
@adswa Thanks! I am yet to fully absorb the plan, but just want to reiterate that 

- we do not have formal notion of "stable" for DataLad itself.  So seeing "stable" for handbook without analog in DataLad tool land sounds confusing to me as a user
- "latest released" DataLad version/tag -> "stable" RTD, "master" (branch) -> "latest" RTD again IMHO just makes it unclear to a new visitor (who sees "latest") either it corresponds to the latest release.  What is your reservation against making it having a clear analogy? "master" DataLad -> "master" RTD handbook, "latest" (or even better "released"?) -> "latest released handbook which describes latest released DatLad"?  IIRC RTD allows for any kind of naming scheme
- "Even though latest is the preferred version that users should read..." why is it preferred if it would be reflecting unreleased API (and possibly replacing released API, e.g. `publish`, while at it) ? Why default reading does not correspond to the version of DataLad users have installed?
- with
```
- ... Unreleased DataLad functionality can be documented here and PR'ed, but it will not be merged unless with a note on required minor DataLad version. If this isn't possible (no released minor DataLad version yet, or expected changes in API or behavior) the PR will simply be kept open. 
```
I expect just an increased burden - possible growth of conflicts etc. But if that works for you -- ok with me of cause ;)  I would find branches easier to manage with master of handbook going along with master branch of the DataLad, while `maint` going after releases.  You could even make `maint` to be the default branch of the handbook so any outside contributor would be submitting by default against `maint` (and you consciously pushing `master` forward with new bleeding edge stuff while `master` of datalad goes forward too). 

Sorry, came out too long ;-)

**Comment by adswa** [comment]
Closing, there is a release management implemented
