### ISSUE TITLE
Start preparing for a 0.13 release

### ISSUE THREAD

**Issue by adswa** [datalad-handbook/book#468]
A DataLad 0.13 release will come in the near-ish rather than distant future. This means we'll also have a 0.13 release of the handbook.

#### definite todos:
- [x] check acknowledgements: Is every contributor in ``.allcontributorsrc`` and is their information in ``.zenodo.json``? I want to make sure that acknowledgement is given for #421 even if this usecase does not make it into the release yet. This is under way on a local branch ``zenodo``, but it is still missing some names from #471.
- [ ] update the CHANGELOG. In progress in #473
- [ ] Tag the repo, make the release

#### really-nice-to-have's:
- [x] It would be superb to have an actually fully working PDF version of the book. What's IMO missing is a clear separation of findoutmore's from the rest of the text. Started in #469, but needs help.
- [ ] Finalize the new four-part structure of the book. #467 can be merged easily, but what's inconvenient is that currently a chapter 11 is missing. Either we'll temporarily rename for the sake of a sequential toctree, or the large work in progress chapters on hirni or the UKB are getting done
- [x] Include all new commands: ``push`` is already in here (and 0.13 will finally solve the mismatch between documentation and release), but ``copy-file`` does not have a chapter yet. Consult DataLad's changelog to see whether there's more. ``create-sibling-ria`` is added in #461 and ``datalad copy-file`` in #476 
- [x] update all examples outputs. I have lost track of what the current summary/output of commands like get or clone are in the lastest released version.

**Comment by adswa** [comment]
release is imminent - wohoo!
