### ISSUE TITLE
Typos and grammar tracking in handbook

### ISSUE THREAD

**Issue by jsheunis** [datalad-handbook/book#733]
This is an issue to track some grammar issues, typos, and other small issues as I read through more parts of the handbook. Will create a PR with many fixes in bulk.

- [x] Section 3.2 broken `find-out-more` tag: https://github.com/datalad-handbook/book/blame/master/docs/basics/101-115-symlinks.rst#L189
- [x] Section 3.2 typo `Its` -> `It's`: https://github.com/datalad-handbook/book/blame/master/docs/basics/101-115-symlinks.rst#L16
- [x] Section 3.2 typo `Its` -> `It's`: https://github.com/datalad-handbook/book/blame/master/docs/basics/101-115-symlinks.rst#L190
- [x] Section 3.2 remove `a`: https://github.com/datalad-handbook/book/blame/master/docs/basics/101-115-symlinks.rst#L297
- [x] Section 9.2 typo `in` -> `is`: https://github.com/datalad-handbook/book/blame/master/docs/basics/101-136-filesystem.rst#L993
- [x] Section 9.2 typo `datasets` -> `dataset's`: https://github.com/datalad-handbook/book/blame/master/docs/basics/101-136-filesystem.rst#L1082
- [x] Use cases typo `NifTi` -> `NIfTI`: https://github.com/datalad-handbook/book/blame/master/docs/usecases/reproducible_neuroimaging_analysis.rst#L144
- [x] Use cases typo `an` -> `and`: https://github.com/datalad-handbook/book/blame/master/docs/usecases/reproducible_neuroimaging_analysis.rst#L254

**Comment by AKSoo** [comment]
- [ ] `disect` -> `dissect` https://github.com/datalad-handbook/book/blob/master/docs/basics/101-122-config.rst
